/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as DashboardIndexImport } from './routes/_dashboard/index'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as DashboardProfileImport } from './routes/_dashboard/profile'
import { Route as DashboardUsersIndexImport } from './routes/_dashboard/users.index'
import { Route as DashboardUsersUserIdImport } from './routes/_dashboard/users.$userId'
import { Route as DashboardUsersUserIdIndexImport } from './routes/_dashboard/users.$userId.index'
import { Route as DashboardUsersUserIdSessionsImport } from './routes/_dashboard/users.$userId.sessions'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

const DashboardProfileRoute = DashboardProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUsersIndexRoute = DashboardUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUsersUserIdRoute = DashboardUsersUserIdImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUsersUserIdIndexRoute = DashboardUsersUserIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersUserIdRoute,
} as any)

const DashboardUsersUserIdSessionsRoute =
  DashboardUsersUserIdSessionsImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => DashboardUsersUserIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileImport
      parentRoute: typeof DashboardImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/users/$userId': {
      id: '/_dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/users/$userId/sessions': {
      id: '/_dashboard/users/$userId/sessions'
      path: '/sessions'
      fullPath: '/users/$userId/sessions'
      preLoaderRoute: typeof DashboardUsersUserIdSessionsImport
      parentRoute: typeof DashboardUsersUserIdImport
    }
    '/_dashboard/users/$userId/': {
      id: '/_dashboard/users/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof DashboardUsersUserIdIndexImport
      parentRoute: typeof DashboardUsersUserIdImport
    }
  }
}

// Create and export the route tree

interface DashboardUsersUserIdRouteChildren {
  DashboardUsersUserIdSessionsRoute: typeof DashboardUsersUserIdSessionsRoute
  DashboardUsersUserIdIndexRoute: typeof DashboardUsersUserIdIndexRoute
}

const DashboardUsersUserIdRouteChildren: DashboardUsersUserIdRouteChildren = {
  DashboardUsersUserIdSessionsRoute: DashboardUsersUserIdSessionsRoute,
  DashboardUsersUserIdIndexRoute: DashboardUsersUserIdIndexRoute,
}

const DashboardUsersUserIdRouteWithChildren =
  DashboardUsersUserIdRoute._addFileChildren(DashboardUsersUserIdRouteChildren)

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRouteWithChildren
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRouteWithChildren,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof DashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/profile': typeof DashboardProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof DashboardIndexRoute
  '/users/$userId': typeof DashboardUsersUserIdRouteWithChildren
  '/users': typeof DashboardUsersIndexRoute
  '/users/$userId/sessions': typeof DashboardUsersUserIdSessionsRoute
  '/users/$userId/': typeof DashboardUsersUserIdIndexRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/profile': typeof DashboardProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof DashboardIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/users/$userId/sessions': typeof DashboardUsersUserIdSessionsRoute
  '/users/$userId': typeof DashboardUsersUserIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/users/$userId': typeof DashboardUsersUserIdRouteWithChildren
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
  '/_dashboard/users/$userId/sessions': typeof DashboardUsersUserIdSessionsRoute
  '/_dashboard/users/$userId/': typeof DashboardUsersUserIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/profile'
    | '/auth/sign-in'
    | '/'
    | '/users/$userId'
    | '/users'
    | '/users/$userId/sessions'
    | '/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/profile'
    | '/auth/sign-in'
    | '/'
    | '/users'
    | '/users/$userId/sessions'
    | '/users/$userId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/profile'
    | '/auth/sign-in'
    | '/_dashboard/'
    | '/_dashboard/users/$userId'
    | '/_dashboard/users/'
    | '/_dashboard/users/$userId/sessions'
    | '/_dashboard/users/$userId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_dashboard",
        "/auth"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/profile",
        "/_dashboard/",
        "/_dashboard/users/$userId",
        "/_dashboard/users/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/sign-in"
      ]
    },
    "/_dashboard/profile": {
      "filePath": "_dashboard/profile.tsx",
      "parent": "/_dashboard"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx",
      "parent": "/auth"
    },
    "/_dashboard/": {
      "filePath": "_dashboard/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/users/$userId": {
      "filePath": "_dashboard/users.$userId.tsx",
      "parent": "/_dashboard",
      "children": [
        "/_dashboard/users/$userId/sessions",
        "/_dashboard/users/$userId/"
      ]
    },
    "/_dashboard/users/": {
      "filePath": "_dashboard/users.index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/users/$userId/sessions": {
      "filePath": "_dashboard/users.$userId.sessions.tsx",
      "parent": "/_dashboard/users/$userId"
    },
    "/_dashboard/users/$userId/": {
      "filePath": "_dashboard/users.$userId.index.tsx",
      "parent": "/_dashboard/users/$userId"
    }
  }
}
ROUTE_MANIFEST_END */
